/// Nhật ký làm sạch dữ liệu
table Cleaning_Log
	lineageTag: 0460d242-43c4-5101-93fc-4dfd8036113a

	column Step
		dataType: string
		lineageTag: a99b5c17-7128-52b2-b08a-422e250c79b1
		summarizeBy: none
		sourceColumn: Step

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: c0b0a424-1bf3-5360-bfc0-04d21df49a6e
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column Rows_Affected
		dataType: int64
		formatString: #,##0
		lineageTag: f86f0bd5-06d8-58ed-aac9-96b039b0a548
		summarizeBy: sum
		sourceColumn: Rows_Affected

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		lineageTag: 4d407f44-dddc-53d4-a10f-1dc9caeaac95
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	column Rows_After
		dataType: int64
		formatString: #,##0
		lineageTag: daf51758-38f8-5788-b5fc-351d96cc639e
		summarizeBy: none
		sourceColumn: Rows_After

		annotation SummarizationSetBy = Automatic

	column Log_Order
		dataType: int64
		formatString: 0
		lineageTag: 5dc89368-666b-581a-8c88-7aa494b7c823
		summarizeBy: none
		sourceColumn: Log_Order

		annotation SummarizationSetBy = Automatic

	partition Cleaning_Log = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVZtaxtHEP4rgyAgw9mWLLl+owU7aW03tuvaglBCMOfT9m7x3a5ytydiyLdAiymluKSUYkqtuMa4jYndpITqKP1wwv/j8ks6s3uKTolxC8kX6d52dp5nnnlm794tbVRKVuk2z5JHAajQLlnV+lTFKt3Kkmfg4+OvY3CzZN+ZheoYvgHhpU8EtHn6m4D0R6jVwcmSn5RZd8/CgNU3AmK0RZ528CZLvgHl8az7TwzlgEcRF+7ILOx46QvhgpM+vz7KQtY9EuB6HJ+kf+EKP+u+bIGS6aGAbczCpPL/A66mR0N4TNjieigv34JmvIufZd1jNXJ9vIZn47LevgQvPeTgp38Id9zNus8E7CBoBSLrXgQgXEmvq6P168OteSninVcq5IpL0V/3BYvG12Rh6cRVyJ7ESHWcdX9HWAgRdyWIs7jaDqN5dVMGLVvswkfQkMr278hwB4uhX75T5GVxMw5DJtSG9BlGH97unULf4crLg6/awnZZ+H7jb3LhsBU7UuuhDKRm/H3Ff4tjjDzvMhiF6nQhZg1jLmq5oJB/hrLLdRdm3Q4n5c1MoSbiwOTCWUQBWRM+BOrKy3OU3lX7vFHwcm8fVe+nhwFkyS8gLjuc9N5xRuDVV9+jxmhL4Xq9U9u0U78bwvTPObi9lD5eW4QHEvu5XK1Z9RvQHDjFiAXuIP12eghN3afb1PIC1kMuw62PH7RYyBlyvWVSVJ69iz/4SYEKbI3SiiTkfX/RBpB8lyeFn19g5AitqZ9gQM2nzLXiyPpnbRZWpy3YVLZo2mFzScZD6p68lm4yQZv7uxu2YuO0NL9clUJ55prQnghNfj8JdXl+2cH/+7GNrpIlBxzyBcvCkQGD8sPwIbza+xUqY5Wa4Txf2vK0v6Ud4ZGKtOWctYiZ5MKZA5OdCiV+WuC8X/q8Mobw3j4KEwOStan0zPHAN3kV0H9A6NFLHS/tarTrLPxShsiiwxAcJwPErfe0DU5AkCWnDpRrFtRHdGlzD97Bbw5a4GkTNlZsYGM4B1t10/btcHeJ7yB0hF2duYGYHwPGebV3PFExd3VDRK6TlpeTGNlcC+O4ZdF2RExv//KchNk9Ag/fYiISE6REAq2LIH2B5vtUeNchHa7IUMkq1sxkDuBTub3C2szXqfX2TTtQieNdSnMOofPBfsRAp88Y/n4r8ozKHsr4pZNXxuy51Y62dOwtYloWx8oUJTsQYsmqT09apU3SeXFUUVHSM5XPJaj2uWtfnmfJET536YJgLX++MQZrruklHzmjth/oa7xgVGQLqLPXs7qxlHWfNqB8P9bK9NO/ifnjFji2tIbS8cn6RO9RMKRosom5HLgv3VE0ShGRxiDnBEM8D6C8zYWgo8AVjBaYQafUE3vweHBPYDBho/jy65FpaQ9o8IBZsMhEk4VoUdRQp3he6J6hnhdiPISwKGqENpbDKNt4mNDT1/FIXx2HXCqf7Ti3x6ujk/iESZ2tIjU65Pun2kpObHMaKXbp8sIqLG0U0MwgmgbWROaV6yP6hNkqDhkw4WJi6JR0IKlV+vUNtDTLOjkr50/FWfIDH7+6phbgMPDI0SkRGlYkjAPHyrWqHXRwXLH6TgGRzPvAtJdj2lA7JYrjhEOIGsCqDp2J/vswGSFmx5vFmZUfAC28LJ7nrNzpqhU0h4LG8m3u/Qs=", BinaryEncoding.Base64), Compression.Deflate)), {"Step", "Action", "Rows_Affected", "Reason", "Rows_After"}),
				    Typed = Table.TransformColumnTypes(Source, {{"Step", type text}, {"Action", type text}, {"Rows_Affected", Int64.Type}, {"Reason", type text}, {"Rows_After", Int64.Type}}),
				    Result = Table.AddIndexColumn(Typed, "Log_Order", 1, 1, Int64.Type)
				in
				    Result

	annotation PBI_ResultType = Table
